### ISSUE TITLE
did not get postman challange points

### ISSUE THREAD

**Issue by vishantrathi** [GSSoC24/Contributor#1027]
### Discussed in https://github.com/orgs/GSSoC24/discussions/1026

<div type='discussions-op-text'>

<sup>Originally posted by **vishantrathi** November  1, 2024</sup>
Hi, I completed challenge adding the relevant links and proofs

Canvas Badges: https://api.badgr.io/public/assertions/6niGQm__To-7rhH-U2SuFw?identity__email=vishantrathigurjar%40gmail.com

Email: vishantrathigurjar@gmail.com

Screenshot of Mail received from Postman 

![image](https://github.com/user-attachments/assets/5e61bf51-d731-42e1-bdb6-36a6a1fd0b92)

@sanjay-kv, @priyanshukumar397, @PRATHAMU200, @shreyash3087, @Jisha-tr please help resolve this
</div>

**Comment by Snehsk** [comment]
Hi @vishantrathi please create a PR for this, then we will merge your PR after 12hrs your points will be reflected in the leaderboard.
