### ISSUE TITLE
Unable to verify email Id and error in downloading certificate 

### ISSUE THREAD

**Issue by yashwanths814** [GSSoC24/Contributor#1093]
![Screenshot_20241111-205810](https://github.com/user-attachments/assets/5536da5b-8fb7-4900-a450-0a2e5dcacdea)
![Screenshot_20241111-205456](https://github.com/user-attachments/assets/698d91bc-7526-4e95-ac34-698df94a730b)

**Comment by yashwanths814** [comment]
@sanjay-kv @AKSHITHA-CHILUKA @Hemu21

**Comment by hemanthkumar-21** [comment]
@yashwanths814 once refresh the page and try now.

**Comment by yashwanths814** [comment]
@Hemu21 Got the certificate,
Thank you 😊
