### ISSUE TITLE
GSSOC Ext ⚠️ SWAGS form is not submitted

### ISSUE THREAD

**Issue by MastanSayyad** [GSSoC24/Contributor#1312]
**Dear Project Admins,**  

This is a gentle reminder to the following individuals:  
- @Yashgabani845 
- @Jaishree2310
- @AlfiyaSiddique
- @DharshiBalasubramaniyam
- @anuj123upadhyay

The swag form sent to you 10 days ago had a submission deadline of **19th November 2024**, but it has not been filled yet. Kindly complete the form **within the next 12 hours.**  

### ⚠️ Important Notes:  
- If you fail to submit the form within this timeframe, **you will be solely responsible for missing out on the swags.**  
- The **GSSoC team will not be held responsible** for any delays caused by incomplete submissions.  

### 📧 Email Details:  
- Please **check your spam folder** to locate the email if it’s not in your inbox.  
- If you still cannot find it, reach out to us within the next 12 hours.  

We appreciate your cooperation!  

Thank you,  
**GSSoC Team**

**Comment by Jaishree2310** [comment]
I have submitted already can you please confirm?

**Comment by Yashgabani845** [comment]
@MastanSayyad  i have just submitted it can you please confirm it

**Comment by MastanSayyad** [comment]
> I have submitted already can you please confirm?

Who is vritika naik, the name is given in your address @Jaishree2310

**Comment by anuj123upadhyay** [comment]
Submitted

**Comment by anuj123upadhyay** [comment]
Submitted

**Comment by Jaishree2310** [comment]
> > I have submitted already can you please confirm?
> 
> Who is vritika naik, the name is given in your address @Jaishree2310 

Sorry got some misunderstanding 
Submitted the form again.
