### ISSUE TITLE
Project Owner Not merge the PR

### ISSUE THREAD

**Issue by ankitgupta143** [GSSoC24/Contributor#214]
Its been almost one week, but my PR is still not merge even the project owner review correctly. #53 issue number in reactchat project

**Comment by AtulYadavCodes** [comment]
try emailing the project admin by email and tell him that the owner has been not accepting pr . they will see the matter or contact the owner

**Comment by sanjay-kv** [comment]
Hi @ankitgupta143 i already answered your question before, 
Your PR has conflict, kindly fix that issue and wait for sometime. maybe before leaderboard our team will go through every PR conflicts and resolve this issue. 

Kindly move on to other issues. Thanks
