### ISSUE TITLE
No Mail received for contributor selection: May 12 2024

### ISSUE THREAD

**Issue by vaidehiiiii-t** [GSSoC24/Contributor#218]
### Discussed in https://github.com/GSSoC24/Contributor/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **sanjay-kv** May 12, 2024</sup>
Write down your name & email ID as comment below. We will check system and send you one asap.</div>

**Comment by vaidehiiiii-t** [comment]
ADITI TRIVEDI
email:- adititrivedi2017@gmail.com
no:- 9839843772

**Comment by sanjay-kv** [comment]
you will get mail shortly.
