### ISSUE TITLE
Not received Mail 23rd May

### ISSUE THREAD

**Issue by swetha-mukku** [GSSoC24/Contributor#230]
name : swetha padmavathi mukku 
email: mswethapadmavathi@gmail.com
discord username : lucky__05

**Comment by Khushhhaaa** [comment]
i also still havwn't received the confirmation mail as a contributor
name: Khushi Soni
mail: Khushis2310@gmail.com or Khushii4sonii@gmail.com

**Comment by ayushkrrana** [comment]
I had registered gssoc with different mail and my github account have another mail , so my contribution point will count or not in the leaderboard ?

**Comment by aryaVishal1706** [comment]
i have some thing i have also 

> I had registered gssoc with different mail and my github account have another mail , so my contribution point will count or not in the leaderboard ?
I have also different email id

**Comment by aasthacodehub** [comment]
I'm still not get any conformation mail... 
Name:- Astha trivedi.. 
Email I'd:- aasthatrivedi6@gmail.com or 
22csel09@kristujayanti.com

**Comment by shreya1826** [comment]
> I'm still not get any conformation mail... Name:- Astha trivedi.. Email I'd:- [aasthatrivedi6@gmail.com](mailto:aasthatrivedi6@gmail.com) or [22csel09@kristujayanti.com](mailto:22csel09@kristujayanti.com)

You can drop your email here for confirmation:-
https://github.com/GSSoC24/Contributor/discussions/227?utm_source=substack&utm_medium=email

**Comment by shreya1826** [comment]
> You can drop your email here for confirmation:-
> https://github.com/GSSoC24/Contributor/discussions/227?utm_source=substack&utm_medium=email



> i also still havwn't received the confirmation mail as a contributor name: Khushi Soni mail: [Khushis2310@gmail.com](mailto:Khushis2310@gmail.com) or [Khushii4sonii@gmail.com](mailto:Khushii4sonii@gmail.com)

You can drop your email here for confirmation:-
https://github.com/GSSoC24/Contributor/discussions/227?utm_source=substack&utm_medium=email

**Comment by shreya1826** [comment]
> name : swetha padmavathi mukku email: [mswethapadmavathi@gmail.com](mailto:mswethapadmavathi@gmail.com) discord username : lucky__05

You can drop your email here for confirmation:-
https://github.com/GSSoC24/Contributor/discussions/227?utm_source=substack&utm_medium=email

**Comment by sanjay-kv** [comment]
> I had registered gssoc with different mail and my github account have another mail , so my contribution point will count or not in the leaderboard ?

i have mentioned this before, it will be counted so don't worry.
