### ISSUE TITLE
MY NAME IS NOT PRESENT ON LEADERBOARD

### ISSUE THREAD

**Issue by Kavin56** [GSSoC24/Contributor#299]
Hi I have contributed to 2 different projects and made 3 successful pull request and it got merged.
but still my username is not present on gssoc leaderboard

https://github.com/shrawani21/gamer_21/pull/43
https://github.com/Kavin56/learn-python/pull/1
https://github.com/Kavin56/learn-python/pull/2

thesr are my 3 merged pull request

**Comment by akashlogics** [comment]
same problem even I have contributed to 2 different projects and made 1 successful pull request.
but still my username is not present on gssoc leaderboard

Clueless-Community/scrape-up

**Comment by SAM-DEV007** [comment]
Tell the PA to add labels to the PR, and assigning the PR to you which was done in the issue. The leaderboard doesn't check the issue but rather checks the merge status of the PR, labels and the assignees to give the points.

**Comment by Kavin56** [comment]
he is not adding bro https://github.com/animator/learn-python

**Comment by Kavin56** [comment]
> same problem even I have contributed to 2 different projects and made 1 successful pull request. but still my username is not present on gssoc leaderboard
> 
> Clueless-Community/scrape-up

is your problem solved?

**Comment by sanjay-kv** [comment]
@Kavin56 None of your PR has labels we will touch with PA directly. give us some time.

**Comment by Kavin56** [comment]
@sanjay-kv is thereany update?

**Comment by akashlogics** [comment]
Sir even my name not present in leaders board I had made 2 PR
