### ISSUE TITLE
When will the leaaderboard get updated?

### ISSUE THREAD

**Issue by ayushkrrana** [GSSoC24/Contributor#348]
Today my level 2 Pr is merged but my points is not added in the leaderboard

**Comment by sanjay-kv** [comment]
Link to PR please

**Comment by ayushkrrana** [comment]
> Link to PR please

https://github.com/Its-Aman-Yadav/Community-Site/pull/531#event-13009562147

**Comment by SalehaTabassum** [comment]
It will get updated two times in a day .so I think  you will soon see your changes .

**Comment by Kalivarapubindusree** [comment]
Leaderboard will update per every 6-12 hrs 
Please check it out later

**Comment by priyanshukumar397** [comment]
check now ! @ayushkrrana
