### ISSUE TITLE
i want to summit a project that i made 

### ISSUE THREAD

**Issue by Jatin9826** [GSSoC24/Contributor#363]
how i  can summit my project i develop a game in python and i want to contribute it .

**Comment by Jatin9826** [comment]
i complete my credit card fraud detection project 
https://github.com/Jatin9826/Credit-card-fraud-detection-using-machine-learning

**Comment by sanjay-kv** [comment]
project acceptance date is over. you can try next year. sorry about that.

**Comment by Jatin9826** [comment]
Ok thanks for your concern
