### ISSUE TITLE
PR not merged

### ISSUE THREAD

**Issue by Apurv7777** [GSSoC24/Contributor#377]
## I have two tasks pending for more than 2 week's now, for the project  [EcommerceSpectastyle](https://github.com/harshalhonde21/EcommerceSpectastyle) .

- Raised https://github.com/harshalhonde21/EcommerceSpectastyle/pull/258 , but no further work on it.
- Raised https://github.com/harshalhonde21/EcommerceSpectastyle/pull/13 , https://github.com/harshalhonde21/EcommerceSpectastyle/pull/27 , but the ***gssoc*** label was not added, thus asking PA to add it.

**Comment by sanjay-kv** [comment]
![image](https://github.com/GSSoC24/Contributor/assets/30715153/68fc2e42-f235-4698-904d-58068a3523e8)

**Comment by Apurv7777** [comment]
Worst PA ever experienced . [EcommerceSpectastyle](https://github.com/harshalhonde21/EcommerceSpectastyle)
