### ISSUE TITLE
Mail for Contributor not received for GSSoC'24

### ISSUE THREAD

**Issue by AnushkaJMokashi** [GSSoC24/Contributor#38]
### Discussed in https://github.com/GSSoC24/Contributor/discussions/5

<div type='discussions-op-text'>
I already filled contributors form on 1st may. But did not received email for contributor.

Email:anushkamokashi@gmail.com
Name:Anushka Mokashi </div>

**Comment by dhyaneshsiddhartha15** [comment]
check your email for a response to see if you have been selected. If you have not received a response, it is possible that you were not selected.

**Comment by AnushkaJMokashi** [comment]
Thank you for considering my issue. I am recieving other GSSOC emails of
newsletter. But not contributor's email.
Kindly refer screenshot below.

**Comment by AnushkaJMokashi** [comment]
> You can do one thing in gmail search for "GSsOC" then see cause it may happen email sent in spam!

Yes I chechked, no mail regarding the contributor's selection is there.

**Comment by bharat3645** [comment]
You can check your mail box, after applying it will take some time to get a mail.

**Comment by Anshikaa-Saini** [comment]
The emails are still being rolled out. Just so you know, you may receive it soon. @AnushkaJMokashi

**Comment by dhyaneshsiddhartha15** [comment]
@AnushkaJMokashi  You can contact the organizer though .

**Comment by AnushkaJMokashi** [comment]
Recieved the contributor's mail about selection. Thank you so much for considering my issue and your support.

**Comment by AnushkaJMokashi** [comment]
Mail for contributor received. Thank you all of you for your time and consideration.
