### ISSUE TITLE
Leaderboard not correct

### ISSUE THREAD

**Issue by AmrutaJayanti** [GSSoC24/Contributor#405]
@admin I totally raised like 7-8 PRs , beofre it showed my rank to be 115 . But today suddenly it is showing me 4 PRs

![Screenshot 2024-06-05 062015](https://github.com/GSSoC24/Contributor/assets/142327526/2abd6ab0-e2bc-4f41-98e2-9eaa819206e4)

Please look into this issue many are facing the same

**Comment by AmrutaJayanti** [comment]
@admin 

Once verify my issue 
![Screenshot 2024-06-05 062802](https://github.com/GSSoC24/Contributor/assets/142327526/0e426b6e-7492-4edf-8af0-e7a1a1d001f3)
You can even check there are projects with GSSOC'24 label merged but not shown in PRs

**Comment by AmrutaJayanti** [comment]
I would provide you the links that are not mentioned in the Leaderboard
[1](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/489#event-13029187614)

[2](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/371)

[3](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/375#event-13014521359)

[4](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/314#event-13007941354)

[5](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/301#event-12996498411)

[6](https://github.com/CodeHarborHub/codeharborhub.github.io/pull/308#event-12997379934)

Please view them .This issues were merged and later were removed by the repo admin . Please count them

**Comment by Yashgabani845** [comment]
@AmrutaJayanti currently leaderboard has not counted any PR of codeharbourhub
i think it is action agiast Spam or some bug 
you guys are spamming over there

**Comment by AmrutaJayanti** [comment]
@sanjay-kv Is the issue resolved ?

**Comment by sanjay-kv** [comment]
> @AmrutaJayanti currently leaderboard has not counted any PR of codeharbourhub i think it is action agiast Spam or some bug

![image](https://github.com/GSSoC24/Contributor/assets/30715153/365e3161-8d08-4b23-affc-0564cf1e1c43)


he changed URL and informed us late, I fixed this issue now.

**Comment by AmrutaJayanti** [comment]
Okay! @sanjay-kv
