### ISSUE TITLE
My pull requests not merged. This is the second time i am opening issue because first one is close without giving any answer.

### ISSUE THREAD

**Issue by VinayLodhi1712** [GSSoC24/Contributor#496]
Links of that pull requests which are not merged :-

https://github.com/TechNodes2-0/ElectiveHub/pull/301
https://github.com/JAYESHBATRA/Virtuo-Learn/pull/446
@sanjay-kv  sir look into this.

**Comment by sanjay-kv** [comment]
I have answered this on the main discussion page.
