### ISSUE TITLE
Leaderboard stopped showing my PRs

### ISSUE THREAD

**Issue by abckhush** [GSSoC24/Contributor#499]
This is to notify you that after the leaderboard was updated today, my previous PRs which were being shown are now not being reflected anymore.
This is today's: ![image](https://github.com/user-attachments/assets/63869c08-e7fc-4fc4-815a-e053ba149781)
This was 2 days ago: ![1](https://github.com/user-attachments/assets/a6c1a34a-d687-484d-9004-e8119b4881db)

My PRs of June 10 are not being reflected anymore. They still have labels and are assigned to me.
![image](https://github.com/user-attachments/assets/a6f7badd-11de-4e92-9cd9-274e61d8699e)

Kindly check @sanjay-kv

**Comment by sanjay-kv** [comment]
i need the link of june 10th PR. so i can cross verify with the system

**Comment by abckhush** [comment]
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/915
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/897

**Comment by abckhush** [comment]
Why is this happening? @sanjay-kv 
In the morning, it was 705 which was wrong, now it has reduced to even less.
![image](https://github.com/user-attachments/assets/77902c32-0271-43c3-bb8e-fd301498e1a1)

**Comment by sanjay-kv** [comment]
It's the repo issue, admin did change the url . We have mentioned not to do anything like that during program. 
We will fix it soon

**Comment by abckhush** [comment]
Ok thankyou so much.

**Comment by abckhush** [comment]
@sanjay-kv 
I'm sorry to disturb you but the total sum of my PRs is also not adding up correctly. Please check.

**Comment by sanjay-kv** [comment]
Hi ik, @Ajay-Dhagar will take care of this, give a week of time

**Comment by abckhush** [comment]
No even the ones that are being reflected right now, the total should add up to 780, it's showing 755.

**Comment by abckhush** [comment]
@sanjay-kv has the issue with CodeHarbor repository been sorted? I still can't see any of my PRs.

**Comment by sanjay-kv** [comment]
you  need to raise a new pr there and mention this issue. i spoke to admin
