### ISSUE TITLE
PR is not labeled

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [GSSoC24/Contributor#510]
@sanjay-kv, One if my prs on repository [eduford university](https://github.com/juhinagpure/Eduford-university) is merged. But not labeled correctly.

Visit the pr [here](https://github.com/juhinagpure/Eduford-university/pull/22).

If it possible, Kindly look into this issue.

**Comment by sanjay-kv** [comment]
Kindly raise the PR in this repo I will merge 
https://github.com/recodehive/machine-learning-repos with same points as I don't have access to that repo

**Comment by DharshiBalasubramaniyam** [comment]
@sanjay-kv, I have raised a pr. Kindly look into that.

This is the pr https://github.com/recodehive/machine-learning-repos/pull/960
