### ISSUE TITLE
Postman point not added on leaderboard 

### ISSUE THREAD

**Issue by Ar7109** [GSSoC24/Contributor#537]
I have completed the GSSOC postman challenge and my pr is also merged, then also the points are not updated on the leaderboard.
Please look into the issue.

**Comment by Ar7109** [comment]
![Uploading Screenshot_2024-07-28-22-46-54-98_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by Ar7109** [comment]
![Screenshot_2024-07-28-22-46-54-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/858230cc-a20a-4068-a357-544a6f9c6a5b)
![IMG_20240728_224345](https://github.com/user-attachments/assets/f71fe3ea-338c-4626-a570-6a19047f68a0)
![Screenshot_2024-07-28-22-42-52-68_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8cb20393-29eb-4a9c-a3ee-9b1fc4e5064a)

**Comment by sanjay-kv** [comment]
there is a bug we are fixing it.

**Comment by Ar7109** [comment]
@sanjay-kv 
Ok sir, thanks a lot for informing.🙏
