### ISSUE TITLE
For someone id, on Leaderboard showing too many PR and points for Postman Challenge.

### ISSUE THREAD

**Issue by ShraddhaSabde** [GSSoC24/Contributor#547]
The postman challenge were added 4 times in the PR list of a person id and points gets added if allowed I can share it
please review that.

**Comment by ShraddhaSabde** [comment]
Please check for this
![pr](https://github.com/user-attachments/assets/8d244a4b-3095-4065-8f26-18a13a173037)

**Comment by sanjay-kv** [comment]
what can we do , they raised too many PR, from our side its very hard to see who did duplicate PR . so now its a double work.

**Comment by sanjay-kv** [comment]
We will fix it once we merge all the PR we recieved.

**Comment by ShraddhaSabde** [comment]
> what can we do , they raised too many PR, from our side its very hard to see who did duplicate PR . so now its a double work.

yes sir

**Comment by ShraddhaSabde** [comment]
> We will fix it once we merge all the PR we recieved.

Ok sir
