### ISSUE TITLE
Verification failed

### ISSUE THREAD

**Issue by ashis2004** [GSSoC24/Contributor#626]
![image](https://github.com/user-attachments/assets/136b1c21-bdeb-4c1e-bf15-54e639e81684)
gmail- ashish_kumar2021@vitbhopal.ac.in
github - [user name - ashis2004](https://github.com/ashis2004)
in leaderboard-
![image](https://github.com/user-attachments/assets/dfcf151e-59f9-4aa0-86e4-b40f8a69d87f)

**Comment by sanjay-kv** [comment]
@Hemu21 can you help him out.

**Comment by Hemu21** [comment]
@ashis2004  you can doenload your certificate after 1 hour
