### ISSUE TITLE
Digital ID Badge Related Queries and Issues

### ISSUE THREAD

**Issue by Synonymous64** [GSSoC24/Contributor#730]
Facing Issues in Downloading Campus Ambassador Badge:

![image](https://github.com/user-attachments/assets/8c401f05-ed43-41a6-89b0-0522609a5af7)

The information that I filled is given below:

![image](https://github.com/user-attachments/assets/5eedae52-9f30-45c5-a6c9-4f5c8171a5e6)

**I checked multiple times there is no extra space in between**

_Kindly help :D_

**Comment by sanjay-kv** [comment]
@Synonymous64

**Comment by MastanSayyad** [comment]
@Synonymous64 I checked it, Its working I can verify and download your badge as well,please provide your details here so that I can download and provide u the badge here

**Comment by Synonymous64** [comment]
Yup, it is working now. I got it! Thanks for the assistance ✨

**Comment by Synonymous64** [comment]
Yup, it is working now. I got it! Thanks for the assistance ✨
