### ISSUE TITLE
verification failed

### ISSUE THREAD

**Issue by Web-Dev-Learner** [GSSoC24/Contributor#738]
I am experiencing an issue while trying to obtain my badge. Upon entering my details, I consistently receive an error message stating, verification failed , "Please type a valid email id and do not give any spaces while you are entering the information." I have double-checked my email and personal details, ensuring there are no spaces or errors. However, I am still encountering the same problem.

Here are the details I am entering:

Email: shribabe2@gmail.com
Role: Contributor
Name: SHRINEDHI M R
Could you kindly assist in resolving this issue? I’ve also tried different browsers, clearing cache, and ensuring no auto-fill is interfering with the process.

I look forward to your guidance.

Thank you for your support.

**Comment by sanjay-kv** [comment]
@MastanSayyad

**Comment by MastanSayyad** [comment]
Hi @Web-Dev-Learner You are not registered as contributor in our database can you please share me the selection mail you have got?

**Comment by Web-Dev-Learner** [comment]
Thank you for reaching out!

I applied to GSSoC as a contributor yesterday, and I haven’t received the
confirmation email yet. I’m currently waiting for the selection mail and
will share it as soon as I receive it.

I appreciate your support and will keep you posted. Thanks again for your
help!

**Comment by MastanSayyad** [comment]
@Web-Dev-Learner You can download your badge when you get the selection mail (Batch 2 will rolled out soon)

**Comment by Web-Dev-Learner** [comment]
Thank you for the clarification and Support
