### ISSUE TITLE
Digital ID Badge Related Queries and Issues

### ISSUE THREAD

**Issue by Akanshaku** [GSSoC24/Contributor#739]
Despite trying so many times I am not able to download badge , there is no extra space in any of my text still its not verifying code you please figure out what's the issue @AKSHITHA-CHILUKA

**Comment by sanjay-kv** [comment]
@MastanSayyad

**Comment by MastanSayyad** [comment]
Hi @Akanshaku Can you provide your details here so that I can provide the badge!

**Comment by Akanshaku** [comment]
> Hi @Akanshaku Can you provide your details here so that I can provide the badge!

email:-akanshakumari3204@gmail.com
name:-Akansha Kumari
Contributor
github:- Akanshaku

**Comment by MastanSayyad** [comment]
any specific img you want to add?

**Comment by Akanshaku** [comment]
> @Akanshaku See it's successfully verified!
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/371398705-f060444a-1d92-461c-804e-b2ac1fec5485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTQyOTMsIm5iZiI6MTcyNzQxMzk5MywicGF0aCI6Ii8xMDE5NzE5ODAvMzcxMzk4NzA1LWYwNjA0NDRhLTFkOTItNDYxYy04MDRlLWIyYWMxZmVjNTQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2M3MGVmOWQ2YjUyMzk4ODVkMTY2NzA1NjNiZjNiNDRiOTU5NDljMGY3MjVkMWM0YzA4YzQ5ZTI2NjRiZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.by5Nn7TM125oAcGKy0_frCHsrFWcEHYSYKhygbuKrnc)
> 
> **Here is your badge:**
> 
> ![Akansha_Kumari_Badge_Contributor_GSSoC2024-Extd](https://private-user-images.githubusercontent.com/101971980/371398784-a00b08da-02ed-41ff-ac55-e439944f79d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTQyOTMsIm5iZiI6MTcyNzQxMzk5MywicGF0aCI6Ii8xMDE5NzE5ODAvMzcxMzk4Nzg0LWEwMGIwOGRhLTAyZWQtNDFmZi1hYzU1LWU0Mzk5NDRmNzlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjBlMWFiMTY0MjdiZjc0NmM1M2VmOTU5NGZmZTE0OTVjYzc1NzJkNzM5OTdiYTZmZDM5ZmM2MjdiMGZkY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.giqkZN25FwV9cnqwSGGlqZ3FRvSakIn9RtsVEozPbvQ)

Thanyou for helping me out.

**Comment by Akanshaku** [comment]
> @Akanshaku See it's successfully verified!
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/371398705-f060444a-1d92-461c-804e-b2ac1fec5485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTQyOTMsIm5iZiI6MTcyNzQxMzk5MywicGF0aCI6Ii8xMDE5NzE5ODAvMzcxMzk4NzA1LWYwNjA0NDRhLTFkOTItNDYxYy04MDRlLWIyYWMxZmVjNTQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2M3MGVmOWQ2YjUyMzk4ODVkMTY2NzA1NjNiZjNiNDRiOTU5NDljMGY3MjVkMWM0YzA4YzQ5ZTI2NjRiZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.by5Nn7TM125oAcGKy0_frCHsrFWcEHYSYKhygbuKrnc)
> 
> **Here is your badge:**
> 
> ![Akansha_Kumari_Badge_Contributor_GSSoC2024-Extd](https://private-user-images.githubusercontent.com/101971980/371398784-a00b08da-02ed-41ff-ac55-e439944f79d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTQyOTMsIm5iZiI6MTcyNzQxMzk5MywicGF0aCI6Ii8xMDE5NzE5ODAvMzcxMzk4Nzg0LWEwMGIwOGRhLTAyZWQtNDFmZi1hYzU1LWU0Mzk5NDRmNzlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwNTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjBlMWFiMTY0MjdiZjc0NmM1M2VmOTU5NGZmZTE0OTVjYzc1NzJkNzM5OTdiYTZmZDM5ZmM2MjdiMGZkY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.giqkZN25FwV9cnqwSGGlqZ3FRvSakIn9RtsVEozPbvQ)

Thankyou for helping me out.
