### ISSUE TITLE
Contribution Consideration without receiving email

### ISSUE THREAD

**Issue by codewithinfiver** [GSSoC24/Contributor#74]
### Discussed in https://github.com/GSSoC24/Contributor/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **codewithinfiver** May 10, 2024</sup>
Hello folks! I have submitted the Contributors Application GSSOC'24 form today. I was a part of the program launch today "Hands-On GSSoC: A Beginner's Guide to Contributing Code" hosted wonderfully by our fellow Program Manager, Sanjay Viswanathan. When could I expect the contributors' acceptance mail so that I could start contributing!? Thank you!</div>

Hello folks, concerning the above discussion will the contributions be considered for the leaderboard if receiving the mail takes a couple of days? Thank you!

**Comment by PRATHAMU200** [comment]
Yes contributions made will be counted, the only requirement is you have to register before 10/05/2024 : 23:59  and you have been selected as contributor. Mail can take time no worries about that.
Talking about leaderboard it will be updated 2 to 3 days after the start of ggsoc24.

**Comment by codewithinfiver** [comment]
> Yes contributions made will be counted, the only requirement is you have to register before 10/05/2024 : 23:59 and you have been selected as a contributor. Mail can take time no worries about that. Talking about the leaderboard it will be updated 2 to 3 days after the start of ggsoc24.

Okay, thank you so much!
