### ISSUE TITLE
Digital ID Badge Related Queries and Issues

### ISSUE THREAD

**Issue by 8uraj** [GSSoC24/Contributor#931]
**i cant get My Badge due to** 

 
![image](https://github.com/user-attachments/assets/73423e3a-9032-45a1-b203-56dd6b09b6ed)
 showing these error 
 
 i am joinnd discord server there have no issue with email but in Badge section these issue occur.

**Comment by anamikarawat2601** [comment]
I am unable to download my badge. I have already checked my email multiple times.

**Comment by 8uraj** [comment]
issue solved
